package com.shanchain.shandata.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.shanchain.shandata.ui.model.ConversationEntry;
import com.shanchain.shandata.ui.model.MessageEntry;

import com.shanchain.shandata.db.ConversationEntryDao;
import com.shanchain.shandata.db.MessageEntryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig conversationEntryDaoConfig;
    private final DaoConfig messageEntryDaoConfig;

    private final ConversationEntryDao conversationEntryDao;
    private final MessageEntryDao messageEntryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        conversationEntryDaoConfig = daoConfigMap.get(ConversationEntryDao.class).clone();
        conversationEntryDaoConfig.initIdentityScope(type);

        messageEntryDaoConfig = daoConfigMap.get(MessageEntryDao.class).clone();
        messageEntryDaoConfig.initIdentityScope(type);

        conversationEntryDao = new ConversationEntryDao(conversationEntryDaoConfig, this);
        messageEntryDao = new MessageEntryDao(messageEntryDaoConfig, this);

        registerDao(ConversationEntry.class, conversationEntryDao);
        registerDao(MessageEntry.class, messageEntryDao);
    }
    
    public void clear() {
        conversationEntryDaoConfig.clearIdentityScope();
        messageEntryDaoConfig.clearIdentityScope();
    }

    public ConversationEntryDao getConversationEntryDao() {
        return conversationEntryDao;
    }

    public MessageEntryDao getMessageEntryDao() {
        return messageEntryDao;
    }

}
